aws_region    = "us-east-1"
instance_type = "t2.micro"
ssh_username  = "ubuntu"    # Default SSH user for Ubuntu
DB_DATABASE   = "health"
DB_USERNAME   = "Aayush"
DB_PASSWORD   = "password"
DB_PORT       = 3306
DB_HOST       = "127.0.0.1"
ROOT_PASSWORD = "password"
