name: Node.js CI with MySQL
env:
  DB_USERNAME: ${{ secrets.NEW_DB_USERNAME }}  # Set DB_USERNAME from new secret
  DB_DATABASE: ${{ secrets.DB_DATABASE }}      # Existing database secret
  DB_PASSWORD: ${{ secrets.NEW_DB_PASSWORD }}  # Set new password secret
  DB_HOST: ${{ secrets.DB_HOST }}               # Existing host secret

on:
  pull_request:
    branches: ["main"]

jobs:
  CI:
    name: Node.JS CI
    runs-on: ubuntu-latest
    steps:
      - name: Install and start MySQL
        run: |
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql.service

      - name: Connect to MySQL and create database
        run: |
          sudo mysql --user="${{ secrets.NEW_DB_USERNAME }}" --password="${{ secrets.NEW_DB_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_DATABASE }};"

      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
