name: Node.js CI with MySQL

on:
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install MySQL as root
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start

    - name: Connect to MySQL and create database
      run: |
         mysql --host 127.0.0.1 -uroot -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
         sudo mysql --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"

    - name: Install Dependencies
      run: sudo npm install  # Adding sudo here for root execution

    - name: Run Tests as root
      run: sudo npm test  # Running tests as root
