name: Node.js CI with MySQL
env:
  DB_USERNAME: ${{ secrets.ALT_DB_USERNAME }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_PASSWORD: ${{ secrets.ALT_DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}

on:
  pull_request:
    branches: ["main"]

jobs:
  CI:
    name: Node.JS CI
    runs-on: ubuntu-latest
    steps:
      - name: Install  and start MySQL
        run: |
          # sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql.service

      - name: Connect to MySQL and create database
        run: |
          sudo mysql --user=${{ secrets.DB_USERNAME }} --password=${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"

      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
